### ISSUE TITLE
LocalStorage or Backend

### ISSUE THREAD

**Issue by jjmontalban** [valefras/MovieStats#2]
Hi

I must to congratulate for you work. I would like to use your app for show my movie information in my web. I can see that you are commented any code about localStorage but my IMDB data have more than 2000 ratings (41MB) and I would like to ask you: Its too much data for localStorage? Do you thinks is better make an api to store my data? You know some similar project that use an Api Laravel to this?

Best regards

**Comment by jjmontalban** [comment]
fine.

**Comment by valefras** [comment]
Hello,
sorry for the late reply, I had read the first message and forgot to
reply... Unfortunately, right now I am working on graduating my bachelor's
degree, so I don't have time to work on personal projects at the moment, my
intentions with regards to MovieStats were to keep working on it after my
graduation and maybe design and develop a Letterboxd-style platform or
simply implement a backend for MovieStats as you suggested.

Best regards
